```uml
@startuml

Entity Проект{
Код проекта
Название проекта
Описание проекта
}

Entity Модуль{
Код проекта
Код модуля
Название модуля
Описание модуля
Элементы серверной части
Элементы клиентской части
Список привязанных пользователей
}

Entity Функциональная_часть{
Код функциональной части
Код модуля
Название функциональной части
Описание функциональной части
Элементы серверной части
Элементы клиентской части
}

Entity Элементы_Серверной_Части{
Код элемента
Название элемента
Название схемы расположения
Тип элемента в БД
}

Entity История_по_элементам_Серверной_Части{
Версия элемента
Статус
Дата
Прогресс выполнения
}

Entity Задачи{
Код продукта
Код модуля
Код функциональной части
Код задачи
Исполнитель
Заказчик
Статус
}

Entity Связь_задачи_с_частями{
Код задачи
Список элементов серверной части
Список элементов клиентской части
}

Entity История_по_элементам_Клиентской_Части{
Название модуля
Процент перевода
Количество функций на Оракле
Количество функций на ПГ
}

Entity Расширенная_история_по_элементам_Клиентской_Части{
Название пакета
Расположение пакета
Процент перевода пакета
Количество функций пакета на Оракле
Количество функций пакета на ПГ
}

Entity Элементы_Клиентской_Части{
Название JAR
Тип файла
Дата изменения файла
Расположение на FTP
Расположение на SVN
}
enum Тип_файла{
Файл существует
Файл не существует
}

Entity Пользователь{
Код пользователя
Логин
Пароль
Тип пользователя
}

enum Тип_пользователя{
Разработчик
Тестировщик
Руководитель
Администратор
}

enum Тип_элемента_БД {
Таблица
Триггер
Пакет
Тип
Представление
Функция
Процедура
}
Пользователь "1 " -.-> "1..n  " Модуль
Тип_файла "1   " --> "1..n" Элементы_Клиентской_Части
Проект "1  " -.-> "1..n  " Модуль
Модуль "1 " -.-> "1..n  " Функциональная_часть
Модуль "1    " --o "1..n      " Элементы_Серверной_Части
Функциональная_часть "1   " --o "1..n  " Элементы_Серверной_Части
Тип_элемента_БД "1 " --> "1..n  " Элементы_Серверной_Части
Модуль "1" --o "1..n        " Элементы_Клиентской_Части
Элементы_Клиентской_Части "1 " --o "1..n " История_по_элементам_Клиентской_Части
История_по_элементам_Клиентской_Части "1 " --o "1..n " Расширенная_история_по_элементам_Клиентской_Части
Элементы_Серверной_Части "1 " --o "1..n " История_по_элементам_Серверной_Части
Тип_пользователя "1 " --> "1..n " Пользователь

Задачи "1 " --> "1..n " Связь_задачи_с_частями
Связь_задачи_с_частями "1 " --> "        1..n" Элементы_Серверной_Части
Связь_задачи_с_частями "1" --> "1..n   " Элементы_Клиентской_Части
@enduml
```