```uml
@startuml
Entity Модуль{
Код проекта
Код модуля
Название модуля
Описание модуля
Элементы клиентской части
}

Entity История_по_элементам_Клиентской_Части{
Название модуля
Процент перевода
Количество функций на Оракле
Количество функций на ПГ
}

Entity Расширенная_история_по_элементам_Клиентской_Части{
Название пакета
Расположение пакета
Процент перевода пакета
Количество функций пакета на Оракле
Количество функций пакета на ПГ
}

Entity Элементы_Клиентской_Части{
Название JAR
Тип файла
Дата изменения файла
Расположение на FTP
Расположение на SVN
}
enum Тип_файла{
Файл существует
Файл не существует
}

Тип_файла "1   " --> "1..n" Элементы_Клиентской_Части
Модуль "1" --o "1..n  " Элементы_Клиентской_Части
Элементы_Клиентской_Части "1 " --o "1..n  " История_по_элементам_Клиентской_Части
История_по_элементам_Клиентской_Части "1 " --o "1..n " Расширенная_история_по_элементам_Клиентской_Части
@enduml
```