```uml
@startuml
Entity Проект{
Код проекта
Название проекта
Описание проекта
Ссылка на задачу в JIRA
}

Entity Модуль{
Код проекта
Код модуля
Название модуля
Описание модуля
Список объектов
Список привязанных пользователей
}

Entity Функциональная_часть{
Код модуля
Код функциональной части
Название функциональной части
Описание функциональной части
Список объектов
}

Entity Задачи_в_JIRA{
Код задачи
Статус задачи
Дата создания задачи
Код проекта
}

Entity Журнал_работ_по_задачам_в_JIRA{
Код строки журнала
Время выполнения задачи
Описание работы
Код задачи
Дата фиксации строки в журнале
}

Entity Объекты_БД{
Код объекта
Название объекта
Схема расположения
Тип объекта
Трудоёмкость
Задача
Список элементов, от которых зависит текущий
Список элементов, которые зависят от текущего
}

Entity Объекты_БД_История{
Дата обновления объекта
Код пользователя
Версия элемента
Тип действия над элементом
Статус
Получить последнюю дату обновления элемента(Код элемента)
Получить последнюю версию элемента(Код элемента)
Получить дату создания элемента(Код элемента)
Получить последнего разработчика элемента(Код элемента)
Получить последнего тестировщика элемента(Код элемента)
Получить последний статус элемента(Код элемента)
}

Entity Пользователь{
Код пользователя
Почта
JWT-токен
Проект
Модуль
Функциональная часть
Функциональная группа
}

enum Функциональная_группа {
Разработчик
Тестировщик
Руководитель
}

enum Статус {
Готово для миграции
Не готово для миграции
Исключить из миграции
В работе
Переведено
Тестируется
Возврат на доработку
Выполнено
}

enum Тип_элемента_БД {
Таблица
Триггер
Пакет
Тип
Представление
Функция
Процедура
}

enum Тип_действия_над_объектом{
Создание
Обновление
Удаление
}

Проект "1  " -.-> "1..n   " Модуль
Модуль "0..1   " -.-> "1..n  " Функциональная_часть
Модуль "1  " --o "1..n    " Объекты_БД
Функциональная_часть "1   " --o "1..n    " Объекты_БД
Тип_элемента_БД "1 " ---> "    1..n" Объекты_БД
Объекты_БД "1..n   " <-- "1    "  Задачи_в_JIRA
Статус "1  " --> "1..n  " Объекты_БД_История
Объекты_БД "1  " --o "1..n      " Объекты_БД_История
Тип_действия_над_объектом "1     " --> "1..n  " Объекты_БД_История
Объекты_БД o-- Объекты_БД
Объекты_БД --o Объекты_БД
Функциональная_группа "1  " --> "1..n   " Пользователь
Пользователь "1  " -.-> "       1..n" Модуль
Задачи_в_JIRA "1 " -.-> "1..n  " Журнал_работ_по_задачам_в_JIRA
Пользователь "1  " -.-> "1..n " Объекты_БД_История
@enduml
```